# Getting Started with Numpy

In [3]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
import numpy as np

In [5]:
lst = [1,2,3,4,5]
print(lst)

[1, 2, 3, 4, 5]


In [6]:
type(lst)

list

In [7]:
arr = np.array(lst)

In [8]:
arr


array([1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [10]:
arr.ndim

1

In [11]:
arr.shape

(5,)

In [12]:
lst = [[1,2,3],[4,5,6]]
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr.ndim

2

In [14]:
arr.shape

(2, 3)

In [15]:
arr.dtype

dtype('int64')

In [16]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((7,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

# Reshape and Random Number Generator

In [18]:
np.random.random((3,4))

array([[0.84189707, 0.4556992 , 0.95585143, 0.30378635],
       [0.97162457, 0.91110619, 0.95960694, 0.83340172],
       [0.49048591, 0.73281296, 0.83717684, 0.81246067]])

In [19]:
np.random.random((4,3))

array([[0.16148315, 0.53694602, 0.37733381],
       [0.6554698 , 0.08946243, 0.6206546 ],
       [0.95036833, 0.45313686, 0.44969527],
       [0.31045053, 0.90878438, 0.99974425]])

In [20]:
if np.random.random() > 0.5:
  print('Run the function.')
else:
  print('Do not run the function')

Run the function.


In [21]:
if np.random.random() > 0.5:
  print('Run the function.')
else:
  print('Do not run the function.')

Do not run the function.


In [22]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [24]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
np.linspace(1,7,10)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])

In [26]:
arr = np.random.random((4,3))

In [27]:
arr

array([[0.22620057, 0.1736457 , 0.83571939],
       [0.96900252, 0.59880453, 0.87561028],
       [0.50201327, 0.25888876, 0.88691514],
       [0.79353295, 0.19990777, 0.04636686]])

In [28]:
np.reshape(arr,(3,4))

array([[0.22620057, 0.1736457 , 0.83571939, 0.96900252],
       [0.59880453, 0.87561028, 0.50201327, 0.25888876],
       [0.88691514, 0.79353295, 0.19990777, 0.04636686]])

In [29]:
np.reshape(arr,(6,2))

array([[0.22620057, 0.1736457 ],
       [0.83571939, 0.96900252],
       [0.59880453, 0.87561028],
       [0.50201327, 0.25888876],
       [0.88691514, 0.79353295],
       [0.19990777, 0.04636686]])

In [30]:
arr.flatten()

array([0.22620057, 0.1736457 , 0.83571939, 0.96900252, 0.59880453,
       0.87561028, 0.50201327, 0.25888876, 0.88691514, 0.79353295,
       0.19990777, 0.04636686])

# Arithmetic Operations on Array

In [31]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
print(arr+1)
print(arr-2)
print(arr/2)
print(arr**2)
print(arr**3)

[ 2  3  4  5  6  7  8  9 10 11]
[-1  0  1  2  3  4  5  6  7  8]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
[  1   4   9  16  25  36  49  64  81 100]
[   1    8   27   64  125  216  343  512  729 1000]


In [33]:
arr += 1
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
arr -= 1
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr *= 3
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [36]:
arr.max()

30

In [37]:
arr.min()

3

In [38]:
arr = np.array([[1,4,7],[2,9,5],[8,3,6]])

In [39]:
arr

array([[1, 4, 7],
       [2, 9, 5],
       [8, 3, 6]])

In [40]:
arr.max()

9

In [41]:
arr.max(axis=0) # Max element col-wise

array([8, 9, 7])

In [42]:
arr.max(axis=1) # Max element row-wise

array([7, 9, 8])

In [43]:
arr.min(axis=0) # Min element col-wise

array([1, 3, 5])

In [44]:
arr.min(axis=1) # Min element row-wise

array([1, 2, 3])

In [45]:
arr.sum() # Sum of all elements in array.

45

# Arithmetic Operations on Multiple Arrays 

In [46]:
arr1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr2 = np.array([[9,8,7],
                 [6,5,4],
                 [3,2,1]])

In [47]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [49]:
arr1 + arr2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [50]:
arr1*arr2

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [51]:
arr1.dot(arr2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [52]:
arr2.dot(arr1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

In [53]:
arr = np.array([1,2,3,4,5])

In [54]:
arr

array([1, 2, 3, 4, 5])

In [55]:
arr[1:]

array([2, 3, 4, 5])

In [56]:
arr[:]

array([1, 2, 3, 4, 5])

In [57]:
arr[2:-2]

array([3])

In [58]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr1[ 1: , 1: ]

array([[5, 6],
       [8, 9]])

In [60]:
arr1[ :1 , :1 ]

array([[1]])

# Array Sorting

In [62]:
arr = np.array([[3,5,2,7,1],[9,3,5,2,8],[3,7,3,7,5,]])

In [63]:
arr

array([[3, 5, 2, 7, 1],
       [9, 3, 5, 2, 8],
       [3, 7, 3, 7, 5]])

In [64]:
arr.sort(axis = 1, kind = 'mergesort')

In [65]:
arr

array([[1, 2, 3, 5, 7],
       [2, 3, 5, 8, 9],
       [3, 3, 5, 7, 7]])

In [66]:
arr.sort(axis = 0, kind = 'mergesort')

In [67]:
arr

array([[1, 2, 3, 5, 7],
       [2, 3, 5, 7, 7],
       [3, 3, 5, 8, 9]])

In [68]:
arr.sort()

In [69]:
arr

array([[1, 2, 3, 5, 7],
       [2, 3, 5, 7, 7],
       [3, 3, 5, 8, 9]])

# Array Merging

In [71]:
arr1 = np.array([[5,2,8,9],[1,7,3,6]])

In [72]:
arr2 = np.array([[1,5,3,9],[2,8,5,4]])

In [73]:
arr1

array([[5, 2, 8, 9],
       [1, 7, 3, 6]])

In [74]:
arr2

array([[1, 5, 3, 9],
       [2, 8, 5, 4]])

In [76]:
np.vstack((arr1,arr2))

array([[5, 2, 8, 9],
       [1, 7, 3, 6],
       [1, 5, 3, 9],
       [2, 8, 5, 4]])

In [77]:
np.vstack((arr2,arr1))

array([[1, 5, 3, 9],
       [2, 8, 5, 4],
       [5, 2, 8, 9],
       [1, 7, 3, 6]])

In [79]:
np.hstack((arr1,arr2))

array([[5, 2, 8, 9, 1, 5, 3, 9],
       [1, 7, 3, 6, 2, 8, 5, 4]])

In [83]:
np.hstack((arr2,arr1))

array([[1, 5, 3, 9, 5, 2, 8, 9],
       [2, 8, 5, 4, 1, 7, 3, 6]])

# Automation using Numpy

In [84]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [85]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [89]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [93]:
print(len(arr[arr > 5]))
print(arr[arr > 5])

5
[ 6  7  8  9 10]


In [102]:
print(len(arr[arr % 2 == 0]))

5


In [99]:
print(arr[arr % 2 == 0])

[ 2  4  6  8 10]
